---
title: "clean_shiny_data"
author: "Declan Molony"
date: "6/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(viridis)
library(lubridate)
library(ggthemes)
library(sp)
library(geojson)
library(geojsonio)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(fmsb)
library(rsconnect)
library(stringr)
library(shinythemes)
library(maps)
library(shiny)
```

```{r}
# Read in World Data
covid <- read.csv("covid_19_data.csv")

# Create results for only the US
data_US <- covid %>%
  filter(Country.Region == "US" & Province.State %in% state.name) %>%
  mutate(ObservationDate = mdy(ObservationDate))
colnames(data_US)[3] <- "States"
colnames(data_US)[7] <- "Death"

# Prepare world data
covid <- covid %>% 
  mutate(ObservationDate = mdy(ObservationDate),
         Country.Region = as.character(Country.Region))

#Clean the country names to work with the geo.json
covid$Country.Region[covid$Country.Region == " Azerbaijan"] <- "Azerbaijan"
covid$Country.Region[covid$Country.Region == "('St. Martin',)"] <- "St. Martin"
covid$Country.Region[covid$Country.Region == "Bahamas"] <- "The Bahamas"
covid$Country.Region[covid$Country.Region == "Bahamas, The"] <- "The Bahamas"
covid$Country.Region[covid$Country.Region == "Congo (Brazzaville)"] <- "Republic of the Congo"
covid$Country.Region[covid$Country.Region == "Congo (Kinshasa)"] <- "Democratic Republic of the Congo"
covid$Country.Region[covid$Country.Region == "Gambia, The"] <- "Gambia"
covid$Country.Region[covid$Country.Region == "Hong Kong"] <- "China"
covid$Country.Region[covid$Country.Region == "Mainland China"] <- "China"
covid$Country.Region[covid$Country.Region == "UK"] <- "United Kingdom"
covid$Country.Region[covid$Country.Region == "North Ireland"] <- "United Kingdom"
covid$Country.Region[covid$Country.Region == "occupied Palestinian territory"] <- "Palestine"
covid$Country.Region[covid$Country.Region == "Republic of Ireland"] <- "Ireland"
covid$Country.Region[covid$Country.Region == "Timor-Leste"] <- "East Timor"
covid$Country.Region[covid$Country.Region == "US"] <- "United States of America"
covid$Country.Region[covid$Country.Region == "West Bank and Gaza"] <- "West Bank"


# Find the totals for each date per country for Confirmed, Deaths, & Recovered
covid <- covid %>% 
  group_by(Country.Region, ObservationDate) %>% 
  summarise(Confirmed = sum(Confirmed), Deaths = sum(Deaths), 
            Recovered = sum(Recovered))

# Read in the geo.json
world_countries <- geojson_read(x = "countries.geo.json", 
                                what = "sp")

# START OF SHINY
# Read in the desired date (this will be the user input for Shiny)
the_fifth <- covid %>% 
  filter(ObservationDate == "2020-06-05")
# Merge the desired date and world country Large SpatialPolygonsDataFrame
world_countries <- merge(world_countries, the_fifth,
                         by.x = "name", by.y = "Country.Region")
```

```{r}
# Old stuff to add United States country data in
# US_rows <- data_US %>% 
#   group_by(ObservationDate) %>% 
#   summarise(Confirmed = sum(Confirmed), Deaths = sum(Deaths), 
#             Recovered = sum(Recovered))
# Country.Region <- rep("United States of America", 103)
# 
# US_total_rows <- cbind(Country.Region,US_rows)
# 
# covid <- rbind(covid, US_total_rows)


# This just tells me how many rows I have for each state
# covidUS %>% 
#   mutate(Province.State = as.character(Province.State)) %>% 
#   group_by(Province.State) %>% 
#   summarise(count = n()) %>% 
#   arrange(Province.State)
```


```{r}
NY <- data_US %>% 
  filter(States == "New York")
```

```{r}
scatter <- data_US %>% 
  filter(States == c(state.name[32],state.name[5])) %>% 
  ggplot() +
    geom_point(mapping = aes(x = ObservationDate, y = Confirmed, 
                             color = States)) +
  ggtitle("Comparison of COVID-19 Impact by State") 

scatter + theme_stata() + scale_color_stata() +
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.title.x = element_text(face = "bold"),
        axis.text.y = element_text(angle = 0),
        title = element_text(face = "bold"))


```

```{r general_info}
covid %>% 
  mutate(Country.Region = as.character(Country.Region)) %>% 
  group_by(Country.Region) %>% 
  summarise(count = n()) %>% 
  arrange(Country.Region)

```

```{r}
world_countries <- geojson_read(x = "countries.geo.json", 
                                what = "sp")

world_countries$name
```







```{r}
covid <- covid %>% 
  mutate(Country.Region = as.character(Country.Region))

countries <- data.frame(unique(covid$Country.Region))
colnames(countries) <- "name"
countries <- countries %>% 
  mutate(name = as.character(name))
countries %>% 
  arrange(name)

```

```{r}
covid$Country.Region[covid$Country.Region == " Azerbaijan"] <- "Azerbaijan"
covid$Country.Region[covid$Country.Region == "('St. Martin',)"] <- "St. Martin"
covid$Country.Region[covid$Country.Region == "Bahamas"] <- "The Bahamas"
covid$Country.Region[covid$Country.Region == "Bahamas, The"] <- "The Bahamas"
covid$Country.Region[covid$Country.Region == "Congo (Brazzaville)"] <- "Republic of the Congo"
covid$Country.Region[covid$Country.Region == "Congo (Kinshasa)"] <- "Democratic Republic of the Congo"
covid$Country.Region[covid$Country.Region == "Gambia, The"] <- "Gambia"
covid$Country.Region[covid$Country.Region == "Hong Kong"] <- "China"
covid$Country.Region[covid$Country.Region == "Mainland China"] <- "China"
covid$Country.Region[covid$Country.Region == "UK"] <- "United Kingdom"
covid$Country.Region[covid$Country.Region == "North Ireland"] <- "United Kingdom"
covid$Country.Region[covid$Country.Region == "occupied Palestinian territory"] <- "Palestine"
covid$Country.Region[covid$Country.Region == "Republic of Ireland"] <- "Ireland"
covid$Country.Region[covid$Country.Region == "Timor-Leste"] <- "East Timor"
covid$Country.Region[covid$Country.Region == "US"] <- "United States of America"
covid$Country.Region[covid$Country.Region == "West Bank and Gaza"] <- "West Bank"
```



```{r}
the_fifth <- covid %>% 
  filter(ObservationDate == "2020-06-05")
```

```{r}
world_countries <- merge(world_countries, the_fifth,
                         by.x = "name", by.y = "Country.Region")
```

```{r}
data.frame(world_countries)
```

```{r}
#This is for the colouring, I used the viridis palette
#It's based on a logarithmic scale
bins <- c(0, 10, 100, 1000, 10000, 100000, 1000000, 10000000)
pal <- colorBin("Reds", domain = world_countries$Confirmed,
                bins = bins)

#This is to set-up a generic leaflet from the data
corona_cases <- leaflet(world_countries) %>% 
  setView(0, 0, 1) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

#This is for the labels when you hover over a country
labels <- sprintf(
  "<strong>%s</strong><br/>%g is the number of<br>coronavirus cases",
  world_countries$name, world_countries$Confirmed) %>%
  lapply(htmltools::HTML)

#This is the entire leaflet
corona_cases %>% 
  #addTiles() to turn the ocean blue
  addTiles() %>% 
  addPolygons(
  #Add colouring to countries
  fillColor = ~pal(Confirmed),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  #Add highlighting when you hover over a country
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  #Labeling for when you hover over a country
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto")) %>% 
  #This is for creating a legend
  addLegend(pal = pal, values = ~Confirmed, opacity = 0.7, 
            title = "Number of coronavirus<br>cases per country",
            na.label = "No data yet",
            position = "bottomright")

```
























